### ISSUE TITLE
what's wrong with this? Anybody can help?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [FreeCodeCamp/FreeCodeCamp#10781]
Challenge [Use Hex Code for Specific Colors](https://www.freecodecamp.com/challenges/use-hex-code-for-specific-colors#?solution=%0A%3Cstyle%3E%0A%20%20body%20%7B%0A%20%20%20%20background-color%3A%20black%3B%0A%20%20%7D%0A%20%20body%7B%0A%20%20%20%20color%3A%20%23000000%3B%0A%20%20%7D%0A%3C%2Fstyle%3E%0A) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

My code:
```html

<style>
  body {
    background-color: black;
  }
  body{
    color: #000000;
  }
</style>

```

**Comment by xgqfrms-GitHub** [comment]
```css
<style>
     body {
       background-color: black;
       color: #000000;
      }
</style>
```

**Comment by xgqfrms-GitHub** [comment]
> Replace the word black in our body element's background-color with its hex code representation, #000000.

I just didn't saw that! 
now everything is fine!
```css
<style>
  body {
    background-color: #000000;
    color: #000000;
  }
</style>
```
