### ISSUE TITLE
Caret icons in challenges list: Right and down animation

### ISSUE THREAD

**Issue by caglayanevren** [freeCodeCamp/freeCodeCamp#13286]
#### Issue Description

If it's proper, may be you want to add these lines to site css for animated caret icons in challenges list. 

#### Your Code

```css
a[aria-expanded=false]>span.no-link-underline>i.fa-caret-down{transform:rotate(-90deg)}
a[aria-expanded=true]>span.no-link-underline>i.fa-caret-right{transform:rotate(90deg)}
a>span.no-link-underline>i.fa-caret-down,
a>span.no-link-underline>i.fa-caret-right{transition:ease 0.2s}
```
#### Screenshot

![src](https://cloud.githubusercontent.com/assets/9939926/22852353/7f943902-f04b-11e6-8ea2-9ba64fa6f929.jpg)

proud to be a camper...
Evren
