### ISSUE TITLE
One of the Layout Tests seems incorrect

### ISSUE THREAD

**Issue by randelldawson** [freeCodeCamp/freeCodeCamp#13356]
Challenge [build-a-technical-documentation-page](http://beta.freecodecamp.com/en/challenges/applied-responsive-web-design-projects/build-a-technical-documentation-page) has an issue.
User Agent is: <code>Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36</code>.
Please describe how to reproduce this issue, and include links to screenshots if possible.

Here is my codepen: http://codepen.io/rmdawson/pen/apKGqW

I believe I may have found a bug with one of the layout test for this Beta project . I am failing the test that checks if my navigation section is all the way over to the left of the screen for laptop and larger screen sizes. The weird thing is, if I change line 45 of my CSS from "top:85px;" to "top:10px" I can pass the test, but then there is a reason I am using the top:85px for the nav links to stay below my nav header.  

Is it possible the test is check for +/ 10px for top and left for the nav?

**Comment by rmdawson71** [comment]
Anybody have a chance to look at this yet?

**Comment by no-stack-dub-sack** [comment]
@rmdawson71 would you mind reopening this issue on the repo that handles the testable projects? 
Here: https://github.com/freeCodeCamp/testable-projects-fcc/issues/new

@bonham000 let me know you opened this a while back. I never saw it because it was in this repo. Sorry about that! If you open it there, we can track and address it. I'll take a closer look at the issue.

**Comment by no-stack-dub-sack** [comment]
Once you reopen it there, please close this issue

**Comment by no-stack-dub-sack** [comment]
@rmdawson71 so it's not so much a bug with the tests, more a failure of the tests to be able to catch every single way their is to implement something. Although there is a way to pass the tests and still achieve the same effect that you're going for...

The header only needs to be `fixed` positioned on smaller screens. When you are making the header fixed, in effect, you are taking it outside of the navbar, and the tests are checking to make sure the navbar is at the top of the page. So just move the rules that do this into the media query and everything will work as you originally intended and pass the tests. 

See below: 

```css
#navbar {
    position: fixed;
    left:0;
    bottom:0;
    top:0;
    width:300px;
    background-color:#f7f7f7;
    border-right: 1px solid #0f034f;
    overflow:auto;  
    padding:10px 0 15px 15px;

}
#navbar header {
    border-right: 1px solid #0f034f;
    border-bottom: 1px solid #0f034f;
    width:315px;
    height:60px;
    background-color:#f3f3f3;
    padding-left:0;
    text-align:center;
    margin-left:-15px;
    padding-top:25px;
}

@media screen and (max-width: 655px) {  
  #navbar header {
    background-color:white;  
    border-top:5px;  
    width:100%;
    border-bottom: 0;  
    position:fixed;
    top:0;
  }  

  #navbar {
    width:90%;
    border:1px solid #0f034f;;    
    height:135px;
    overflow: auto;
    margin-left:15px;
    margin-right:15px;
    padding-top:10px;  
    top: 85px; 
  } 
}
```
