### ISSUE TITLE
Update Map's Estimated Time Style

### ISSUE THREAD

**Issue by virtual** [freeCodeCamp/freeCodeCamp#16321]
#### Challenge Name
Any challenge showing the [map](https://beta.freecodecamp.org/en/challenges/applied-accessibility/use-headings-to-show-hierarchical-relationships-of-content)

#### Issue Description
The estimated time is not accessible with the current color `#bbbbbb`; since it is also rather large and taking up some real estate, I'd propose making it darker `#555555` to pass WCAG 2.0 AA. This will also allow it to be smaller and normal font style as it's not so light and hard to read at a small font size.

#### Proposed Style Code
```css
.map-block-time {
    color: #555;
    font-weight: normal;
    font-size: 1.4rem;
}

```
#### Screenshot
Proposed update:
![Estimated challenge time proposed design](https://i.imgur.com/V5yhDFP.png)
