### ISSUE TITLE
Docker: shared networking, custom image / tag

### ISSUE THREAD

**Issue by ojongerius** [freeCodeCamp/freeCodeCamp#16936]
Started writing this as comment on an issue in https://github.com/freeCodeCamp/open-api/issues/20 but figured if I discuss here we have more eyes/brains in the conversation. Context: we have another project called open-api that, at least for a while will use the same same database as freecodecamp:

@raisedadead curious about your thoughts here; as a developer I would prefer not to rely on having to clone and run the main freeCodeCamp repository if I just want to work on open-api.

I have a few suggestions:

* Create a Docker image based on mongo and us that in both repos
* Using over ride files to allow developers to start the main repo with or without sharing the network (the default would be without, ie the old behaviour, an options would be to share for other repos to use), and for devs on open-api to chose to either use the shared db or a separate one.

Devs will be able to chose how switch between 2 modes. The default `docker-compose up` works like it currently does, in isolution, but adding an override will allow sharing.

Start fcc with shared networking, first from freecodecamp/freecodecamp, then from freecodecamp/open-api:

`docker-compose up -f docker-compose-shared-network.yml`

## Docker images
I dislike having to maintain mongodb images/configs for 2 repositories. And for a while we'll be in this annoying temporary situation where 2 services will communicate with the same MongoDB cluster.

How about publishing our own MondoDB image, and pull latest from that one, from both freeCodeCamp and open-api? In that way if someone wants to bump the MondoDB version they will to it for both repositories.

Both repositories will use their own docker-compose file, but instead of pulling `mongo:3.2.6` they'll pull `freecodecamp/mongo:production` (or whatever tag we want to use).

The `freecodecamp/mongo` image does not have to be more than one line, we build tag and push to the registry and use that to coordinate the version.

```
FROM mongo:3.2.6
```

## Managing networking across repositories
This can be done like so, happy to hear other solutions:
* Add a shared network to the main repo
* Use the shared network in other repos like open-api

Config could look like so, examples are from customised docker-compose file, I'll create a PR using override files:

Freecodecamp repo docker-compose or over rides would contain:

```
networks: # Used by by other projects like open-api
    shared:
        driver: bridge
```
And services would use it like so:

```
   db:
        image: freecodecamp/mongo:production
        ports:
            - "27017:27017" # Change port if needed
        networks:
            - shared
   freecodecamp:
        image: node:8.9.0
        depends_on:
            - db
        environment:
            - MONGOHQ_URL=mongodb://db:27017/freecodecamp
        volumes:
            - .:/fcc
        working_dir: /fcc
        command:
            - npm
            - run
            - develop
        ports:
            - "3000:3000" # Change port if needed
        networks:
            - shared
```

Other repos, like this repo:

```
networks: # re-use fcc network
    freecodecamp_shared:
        external: true
```

And services use it like so:
```
        networks:
            - freecodecamp_shared
```
Chores if we implement this:
- [ ] ~~Publish image to Docker hub~~
- [x] Update CONTRIBUTING
- [x] Bump node and mongo to LTS versions, do the same for open-api
