### ISSUE TITLE
<wbr> showing up in test results section

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#35004]
**Describe your problem and how to reproduce it:**
It was reported in a [recent forum topic](https://www.freecodecamp.org/forum/t/spinal-tap-case-bug-in-test/255559) that the test text was mentioning something about `<wbr>` in the test results section (fake console) on the production site.  I did some searching throughout the `master` branch code and found three challenges (see below) which have such text in them.

Users with incorrect solutions are seeing these `<wbr>`s in the test results and are not sure if they need to add them to their solution.  With a correct solution, the user never sees these, but this should be resolved so as not to confuse users who are trying to create a passing solution.

**Add a Link to the page with the problem:**

I have only linked to the English version of the three challenges, but this issue affects all the languages.

[Intermediate Algorithm Scripting: Spinal Tap Case](https://learn.freecodecamp.org/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/spinal-tap-case/)
```yml
  - text: <code>spinalCase("thisIsSpinal<wbr>Tap")</code> should return <code>"this-is-spinal-tap"</code>.
    testString: assert.strictEqual(spinalCase('thisIsSpinalTap'), "this-is-spinal-tap", '<code>spinalCase("thisIsSpinal<wbr>Tap")</code> should return <code>"this-is-spinal-tap"</code>.');
  - text: <code>spinalCase("The_Andy_<wbr>Griffith_Show")</code> should return <code>"the-andy-griffith-show"</code>.
    testString: assert.strictEqual(spinalCase("The_Andy_Griffith_Show"), "the-andy-griffith-show", '<code>spinalCase("The_Andy_<wbr>Griffith_Show")</code> should return <code>"the-andy-griffith-show"</code>.');
```
---
[jQuery: Learn How Script Tags and Document Ready Work](https://learn.freecodecamp.org/front-end-libraries/jquery/learn-how-script-tags-and-document-ready-work/)
```yml
  - text: 'You should add <code>$&#40;document&#41;.ready<wbr>&#40;function&#40;&#41; {</code> to the beginning of your <code>script</code> element.'
    testString: 'assert(code.match(/\$\s*?\(\s*?document\s*?\)\.ready\s*?\(\s*?function\s*?\(\s*?\)\s*?\{/g), "You should add <code>$&#40;document&#41;.ready<wbr>&#40;function&#40;&#41; {</code> to the beginning of your <code>script</code> element.");'
  - text: 'Close your <code>$&#40;document&#41;.ready<wbr>&#40;function&#40;&#41; {</code> function with <code>}&#41;;</code>'
    testString: 'assert(code.match(/\n*?\s*?\}\s*?\);/g), "Close your <code>$&#40;document&#41;.ready<wbr>&#40;function&#40;&#41; {</code> function with <code>}&#41;;</code>");'
```
---

[Basic HTML and HTML5: Link to External Pages with Anchor Elements](https://learn.freecodecamp.org/responsive-web-design/basic-html-and-html5/link-to-external-pages-with-anchor-elements/)
```yml
  - text: You need an <code>a</code> element that links to <code>http&#58;//freecatphotoapp<wbr>.com</code>
    testString: assert(/http:\/\/(www\.)?freecatphotoapp\.com/gi.test($("a").attr("href")), 'You need an <code>a</code> element that links to <code>http&#58;//freecatphotoapp<wbr>.com</code>');
```

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/5313213/52000233-6ec7c100-2471-11e9-8efa-cb830dd6a800.png)
