### ISSUE TITLE
Recommend using semantic markup for code

### ISSUE THREAD

**Issue by ojeytonwilliams** [freeCodeCamp/freeCodeCamp#35913]
In the description and instruction sections of the challenges, the style guide recommends `<blockquote>` to markup blocks of code, and `<code>` for inline code.  

I think it would be better to be consistent and use semantic markup for both.

We could either do this by through `<pre><code>` tags or take advantage of the fact we're using markdown and use code fences, i.e. \```js ```.  This would have the benefit that we could use prismjs to make the code highlighting in the challenge descriptions the same as in the guide.

**Comment by RandellDawson** [comment]
I made the following changes to `client/src/templates/Challenges/components/challenge-description.css`

```css
.challenge-instructions {
  font-size: 16px;
}

.challenge-instructions blockquote, .challenge-instructions pre {
  background-color: #eee;
  color: #c7254e;
  padding: 10px;
  width: 100%;
  margin: 0;
  margin-bottom: 1.45rem;
  font-family: monospace;
  font-size: 16px;
}

.challenge-instructions pre {
  border: 0;
  border-radius: 0%;
}
```
This allows the current way we are writing the `blockquote` code sections to look the same as long as the  the code written immediately follows the `<code>` tag and the `</code>` tag immediately follows the written code.  

For example, with the above CSS change, both of the following render exactly the same.
```html
<blockquote>
{<br>
&nbsp;&nbsp;Alan: {<br>
&nbsp;&nbsp;&nbsp;&nbsp;online: false<br>
&nbsp;&nbsp;},<br>
&nbsp;&nbsp;Jeff: {<br>
&nbsp;&nbsp;&nbsp;&nbsp;online: true<br>
&nbsp;&nbsp;},<br>
&nbsp;&nbsp;Sarah: {<br>
&nbsp;&nbsp;&nbsp;&nbsp;online: false<br>
&nbsp;&nbsp;}<br>
}</blockquote>

<pre><code>{
  Alan: {
    online: false
  },
  Jeff: {
    online: true
  },
  Sarah: {
    online: false
  }
}</code></pre>
```
If the `<code>` tag` is on a separate line which would make it more readable (like below), then there would be an extra line space at the top (see very bottom screenshot). 
```html
<pre><code>
{
  Alan: {
    online: false
  },
  Jeff: {
    online: true
  },
  Sarah: {
    online: false
  }
}
</code></pre>
```
![image](https://user-images.githubusercontent.com/5313213/56755105-93b39380-6743-11e9-9704-74c40d81c67d.png)

>or take advantage of the fact we're using markdown and use code fences, i.e. ```js ```. This would have the benefit that we could use prismjs to make the code highlighting in the challenge descriptions the same as in the guide.

I really like the idea of being able to use the  ```js ``` markdown format, but if we could be OK with making sure to start the code immediately after the `<pre><code>`, that is a huge improvement over how we are having to write the `blockquote`s currently.
