### ISSUE TITLE
Responsive Web Design Principles: Create a Media Query: test is passed bug

### ISSUE THREAD

**Issue by jippy89** [freeCodeCamp/freeCodeCamp#36071]
**Describe your problem and how to reproduce it:**
At first I had trouble finishing the course, **at first I thought that it was a bug,** turns out it's the same as issue #16474. However I managed to pass **without doing that.**

Here's what I do instead:
```css
p {
    font-size: 10px;    /* change this from 20px to 10px */
  }

  /* Add media query below */
@media (max-height: 800px) {
    
}
```

**Add a Link to the page with the problem:**
[Responsive Web Design Principles: Create a Media Query](https://learn.freecodecamp.org/responsive-web-design/responsive-web-design-principles/create-a-media-query/)

**Tell us about your browser and operating system:**
* Browser Name: Firefox
* Browser Version: 66.0.5 (64-bit)
* Operating System: 
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	18.0.4
Codename:	Illyria
