### ISSUE TITLE
Empty white space between the navbar and main content under dark theme. 

### ISSUE THREAD

**Issue by cryptographicfool** [freeCodeCamp/freeCodeCamp#36335]
**Describe the bug**
On the curriculum page, there is empty white space between the navbar and main content when viewed in dark theme. 

**To Reproduce**
1. Go to 'https://learn.freecodecamp.org/'
2. Make sure you have dark/night theme enabled.
3. Scroll all the way up and notice a white space visible just under the navigation nbar.

**Expected behavior**
There should not be any white space and the green should transition straight to dark grey. (Unless this is a design choice, but I don't think so as the same white space is not visible on other pages.)

**Screenshots**
![Screenshot-2019-6-27 Welcome to learn freeCodeCamp ](https://user-images.githubusercontent.com/51486480/60224398-d4dd3680-989f-11e9-9979-c974abfbd9f9.png)

**Desktop (please complete the following information):**
 - OS: Debian Stretch
 - Browser: Firefox

**Additional context**
Nothing else, the above explains the issue. 

Thank you!

**Comment by cryptographicfool** [comment]
An update on the white space issue, it is visible on all pages under learn.freecodecamp.org.

Screen-shots for reference:
![Screenshot-2019-6-27 Responsive Web Design Projects - Build a Personal Portfolio Webpage Learn freeCodeCamp}](https://user-images.githubusercontent.com/51486480/60271741-874ce200-9910-11e9-80a3-d70185f7c08b.png)
![Screenshot-2019-6-27 Basic JavaScript Compound Assignment With Augmented Division Learn freeCodeCamp](https://user-images.githubusercontent.com/51486480/60271754-8ae06900-9910-11e9-8e0a-b8c0a7d918f6.png)


I have tested the same on:

OS: 
- MacOS
- Debian
- Ubuntu
- Fedora

Browsers: 
- Safari
- Firefox
- GoogleChrome

**Comment by godcrampy** [comment]
Can you specify the versions of the web browsers. I tried the following setup but could not reproduce this behavior:

OS: 
* Fedora 30

Browsers:
* Mozilla Firefox 67.0.4
* Google Chrome 75.0.3770.100

**Comment by webdevdaemon** [comment]
I can fix this with a 2 line edit to the stylesheet, I found the problem in DevTools:

```css
.app-wrapper {
    margin-top: 38px;
    min-height: calc(100vh - 38px);
}
```
Should Be:
```css
.app-wrapper {
    margin-top: 36px;
    min-height: calc(100vh - 36px);
}
```

I'm gonna go ahead and submit a PR with this fix, I see that this has already been assigned to a dev, but it isn't fixed yet, and I know how busy everyone is around here with the doing God's work, saving lives, and transforming careers.

Let me know if there is a problem with me working on this, or with my solution, etc.

Thank You,
{cm}

_PS: another option could be to alter the height of the header itself, an even simpler 1-line solution:_

```css
#top-nav {
    background: #006400;
    margin-bottom: .45rem;
    height: 36px; /* change to: */ height: 38px;
    margin-bottom: 0;
    border-radius: 0;
    border: none;
    -ms-flex-pack: justify;
    justify-content: space-between;
    padding: 0 30px 0 15px;
}
```

_I think I'll go with that instead for my initial PR..._
