### ISSUE TITLE
Microservices Projects tests don't work

### ISSUE THREAD

**Issue by sashko02309178409** [freeCodeCamp/freeCodeCamp#36467]
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/05-apis-and-microservices/apis-and-microservices-projects/timestamp-microservice.english.md 

The tests for projects are not working anymore.
Campers can submit any random URL to pass their challenges.
This bug turns off people from Freecodecamp, cause you never know if you accomplished a challenge or not.

Here is a discussion of this problem on FreeCodeCamp forum
https://www.freecodecamp.org/forum/t/timestamp-microservice-how-to-test-that-api/290578/10

As I can see there were tests
```
tests:
  - text: 'It should handle a valid date, and return the correct unix timestamp'
    testString: 'getUserInput => $.get(getUserInput(''url'') + ''/api/timestamp/2016-12-25'').then(data => { assert.equal(data.unix, 1482624000000, ''Should be a valid unix timestamp''); }, xhr => { throw new Error(xhr.responseText); })'
- text: 'It should handle a valid date, and return the correct UTC string'
    testString: 'getUserInput => $.get(getUserInput(''url'')+ ''/api/timestamp/2016-12-25'').then(data => { assert.equal(data.utc, ''Sun, 25 Dec 2016 00:00:00 GMT'', ''Should be a valid UTC date string''); }, xhr => { throw new Error(xhr.responseText); })'
  
``` 
But they are not working.

This is the same for all Microservices Projects.
