### ISSUE TITLE
non-English curriculum certificate files

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#37215]
As I was attempting to fix some broken Portuguese challenges after running `npm run test:curriculum` for the Portuguese challenge files, I noticed the following failure:
```
Testing

  0 passing (615ms)
  1 failing

  1) Check challenges
       Check challenges (portuguese)
         Legacy Front End Certificate
           Common checks:
     AssertionError: ValidationError: child "tests" fails because ["tests" at position 0 does not match any of the allowed types]
      at Context.<anonymous> (test\test-challenges.js:164:19)
```

After looking at [the file in with the error](https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/portuguese/09-certificates/legacy-front-end-certificate/legacy-front-end-certificate.portuguese.md), I noticed the Tests section looked like:
````
## Tests
<section id='tests'>

```yml
tests:
  - text: ''
    testString: !<tag:yaml.org,2002:js/undefined> ''
  - text: ''
    testString: !<tag:yaml.org,2002:js/undefined> ''
  - text: ''
    testString: !<tag:yaml.org,2002:js/undefined> ''
  - text: ''
    testString: !<tag:yaml.org,2002:js/undefined> ''
  - text: ''
    testString: !<tag:yaml.org,2002:js/undefined> ''
  - text: ''
    testString: !<tag:yaml.org,2002:js/undefined> ''
  - text: ''
    testString: !<tag:yaml.org,2002:js/undefined> ''
  - text: ''
    testString: !<tag:yaml.org,2002:js/undefined> ''
  - text: ''
    testString: !<tag:yaml.org,2002:js/undefined> ''
  - text: ''
    testString: !<tag:yaml.org,2002:js/undefined> ''

```

</section>
````
I checked the English version and the other non-English versions and noticed that the English and Russian versions are identical (see below) and the other languages (Arabic, Chinese, Portuguese, and Spanish) look the same as above.
````
## Tests
<section id='tests'>

```yml
tests:
  - id: bd7158d8c242eddfaeb5bd13
    title: Build a Personal Portfolio Webpage
  - id: bd7158d8c442eddfaeb5bd13
    title: Build a Random Quote Machine
  - id: bd7158d8c442eddfaeb5bd0f
    title: Build a Pomodoro Clock
  - id: bd7158d8c442eddfaeb5bd17
    title: Build a JavaScript Calculator
  - id: bd7158d8c442eddfaeb5bd10
    title: Show the Local Weather
  - id: bd7158d8c442eddfaeb5bd1f
    title: Use the Twitch JSON API
  - id: bd7158d8c442eddfaeb5bd18
    title: Stylize Stories on Camper News
  - id: bd7158d8c442eddfaeb5bd19
    title: Build a Wikipedia Viewer
  - id: bd7158d8c442eedfaeb5bd1c
    title: Build a Tic Tac Toe Game
  - id: bd7158d8c442eddfaeb5bd1c
    title: Build a Simon Game
```

</section>
````

I researched a bit more and noticed that all the files in the certifications folder for these same languages look the same, should we make the Arabic, Chinese, Portuguese, and Spanish versions like the English and Russian?  I am also wondering if the `title` properties are supposed to be translated (even for the Russian version).
Should the other 4 non-English version of this file
