### ISSUE TITLE
Small bug in the Create a Hash table challenge

### ISSUE THREAD

**Issue by RandellDawson** [freeCodeCamp/freeCodeCamp#37577]
**Describe your problem and how to reproduce it:**
The Create a Hash table challenge has a bug in the 2nd to last test (see below):
```yml
  - text: Items are added using the hash function.
    testString: assert((function() { var test = false; if (typeof HashTable !== 'undefined') { test = new HashTable() }; called = 0; test.add('key1','value1'); test.add('key2','value2'); test.add('key3','value3'); return (called === 3)})());
  - text: The hash table handles collisions.
```
The problem is if the user's code calls the `hash` function more than once, then the the `called` variable will be greater than 3.  [This forum topic](https://www.freecodecamp.org/forum/t/having-trouble-with-create-a-hash-table-challenge/324284) shows an example of a solution that should technically pass all of the tests, but fails the 2nd to last test due to calling the `hash` function two times (once with the `hasOwnProperty` and again within the ternary expression.

**Proposed Solution:**
Since, we are trying to confirm there are `3` adds executed, we could just validate that `called` is greater or equal than `3` AND `called % 3` is equal to `0`.  

What does everyone think about my proposed solution?

**Add a Link to the page with the problem:**
https://www.freecodecamp.org/learn/coding-interview-prep/data-structures/create-a-hash-table
