### ISSUE TITLE
CSS Grid: Comment in the CSS

### ISSUE THREAD

**Issue by caleb-mabry** [freeCodeCamp/freeCodeCamp#38310]
**Describe your problem and how to reproduce it:**

The code is listed as 
```css
  .container {
    font-size: 40px;
    min-height: 300px;
    width: 100%;
    background: LightGray;
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: 1fr 1fr 1fr;
    grid-gap: 10px;
    grid-template-areas:
    /* Only change code below this line */
      "header header header"
      ". content content"
      "footer footer footer";
    /* Only change code above this line */
  }
``` 
When you try to submit it is failing because there is a comment in the `grid-template-areas`. If you move the comment outside of the `grid-template-areas` the code will pass. I believe it would be better to have put it as:
```css
  .container {
    font-size: 40px;
    min-height: 300px;
    width: 100%;
    background: LightGray;
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    grid-template-rows: 1fr 1fr 1fr;
    grid-gap: 10px;
    /* Only change code below this line */    <-- This will cause the test to pass
    grid-template-areas:
      "header header header"
      ". content content"
      "footer footer footer";
    /* Only change code above this line */
  }
```
**Add a Link to the page with the problem:**
[https://www.freecodecamp.org/learn/responsive-web-design/css-grid/divide-the-grid-into-an-area-template](https://www.freecodecamp.org/learn/responsive-web-design/css-grid/divide-the-grid-into-an-area-template)

**Tell us about your browser and operating system:**
* Browser Name: Firefox Developer Edition
* Browser Version: 74.0b9
* Operating System: macOS Mojave 10.14.6

**If possible, add a screenshot here (you can drag and drop, png, jpg, gif, etc. in this box):**
![image](https://user-images.githubusercontent.com/36182383/75686988-1910aa00-5c6b-11ea-81e1-3b485a34ae53.png)
