### ISSUE TITLE
Latest Helmet Version Unsupported in Hide Potentially Dangerous Information

### ISSUE THREAD

**Issue by skaparate** [freeCodeCamp/freeCodeCamp#39462]
Hello!

**Describe your problem and how to reproduce it:**

A user on the forum reported that he couldn't finish the challenge **Hide Potentially Dangerous Information Using Helmet PoweredBy**. Upon further investigation, I found that the API of helmet in 4.+ has changed, which causes problems with the validation of the challenge.

Using version 4.1.0 of helmet, this is the response from the server:

```
{"headers":{},"appStack":["xPoweredByMiddleware"]}
```

Whereas on version 3.+, the response is this:

```
{"headers":{},"appStack":["hidePoweredBy"]}
```

Which is the response expected by the test (`assert.include(data.appStack, 'hidePoweredBy');`):

```yaml
tests:
  - text: helmet.hidePoweredBy() middleware should be mounted correctly
    testString: getUserInput => $.get(getUserInput('url') + '/_api/app-info').then(data => { assert.include(data.appStack, 'hidePoweredBy'); assert.notEqual(data.headers['x-powered-by'], 'Express')}, xhr => { throw new Error(xhr.responseText); })
```

**Add a Link to the page with the problem:**

https://www.freecodecamp.org/learn/information-security/information-security-with-helmetjs/hide-potentially-dangerous-information-using-helmet-hidepoweredby

You can see it working here:

Helmet 4.1.0 (doesn't pass the challenge): https://repl.it/@skaparate/infosec-hide-poweredby-helmet410
Helmet 3.23.3 (this does pass): https://repl.it/@skaparate/infosec-hide-poweredby-helmet3233

Maybe, for compatibility, [it could be fixed by modifying the boilerplate](https://repl.it/@skaparate/infosec-hide-poweredby-helmtet4-fix#server.js) and replacing the stack name `xPoweredByMiddleware` with the old name?:

```
// Source: https://github.com/freeCodeCamp/boilerplate-infosec/blob/b6de80bce9429016ca795a928f54825b74f425fa/server.js#L35

var appMainRouteStack = main._router.stack
    .filter(s => s.path === '')
    .map(l => {
      if (l.name === 'xPoweredByMiddleware') {
        return 'hidePoweredBy'
      }
      return l.name
    })
    // filter out express default middlewares
    .filter(n => !(n === 'query' ||
      n === 'expressInit' || n === 'serveStatic'));
```
