### ISSUE TITLE
News section - Table cells don't allow wrapping of text

### ISSUE THREAD

**Issue by robole** [freeCodeCamp/freeCodeCamp#39737]
All tables are very wide and require a horizontal scrollbar. Text does not wrap, so everything is forced onto a single line in a cell.

![table-scroll](https://user-images.githubusercontent.com/3703647/94694541-8bfc1380-0367-11eb-9791-78c6c617be17.png)

## Link

Any article with a table.

## Fix

It should be resolved by removing the property below:

```css
.post-full-content table {
    white-space: nowrap;
}
```
