### ISSUE TITLE
'help us translate' badge link is breaking the layout on mobile/smaller screens

### ISSUE THREAD

**Issue by kelvinsanchez15** [freeCodeCamp/freeCodeCamp#41266]
**Describe the bug**
The link to the i18n contribution docs is breaking the layout on mobile/smaller screens.

**To Reproduce**
Steps to reproduce the behavior (Try this on a mobile device or change your window viewport to a smaller one):
1. Go to https://www.freecodecamp.org/espanol/learn/javascript-algorithms-and-data-structures/
2. Scroll down to 'Cursos'
3. See how 'Ayúdanos a traducir' link is breaking the layout

**Expected behavior**
It shouldn't break the layout. In that breakpoint the usual thing is that each element remains on a different line.

**Screenshots**
![image](https://user-images.githubusercontent.com/4708484/109233201-d8753f00-779f-11eb-8d1b-70d8e04d3082.png)

**Comment by ahmadabdolsaheb** [comment]
Thanks for reporting this issue:

An easy way to tackle this would be to remove the `no-wrap` to add the followings:

```css
.block-cta-wrapper {
  /* white-space: nowrap;*/
  flex-grow: 2;
  flex-basis: 0;
  font-size: 0.8rem;
  text-align: center;
}
```
 ```css
.block-title-wrapper .block-link {
    flex-grow: 3;
    flex-basis: 0;
}
```
