### ISSUE TITLE
Add Different Padding to Each Side of an Element issue

### ISSUE THREAD

**Issue by powhunter158** [FreeCodeCamp/FreeCodeCamp#4292]
Whenever adding padding to my green-box element, the top line, whichever side is written, never registers as completed. I've tried all sides, spaces, and unsure if there is a bug here?
![screen shot 2015-11-10 at 9 45 58 pm](https://cloud.githubusercontent.com/assets/13262195/11082583/822cbc22-87f4-11e5-8e3b-e96c30a1c2a0.png)

**Comment by SaintPeter** [comment]
The problem is that you forgot a semi-colon on the line above your `padding-top`:
```css
.green-box {
    background-color: green;   /* <-- You needed a semicolon here */
    padding-top: 40px;
    padding-left: 40px;
    padding-right: 20px;
    padding-bottom: 20px;
  }
```

In the future, please do two things:

1. If you have a question about your code, try using the "help" button and asking in chat.  We have many dedicated helpers who can easily answer this question.
2. If you genuinely believe there is a problem with the site, please use the "bug" button which will submit your code as text, making it significantly easier for us to diagnose your issue.

Closing as there is no site issue.
