### ISSUE TITLE
RWD Beta: Rothko lesson Step 37 is wrong

### ISSUE THREAD

**Issue by Kernix13** [freeCodeCamp/freeCodeCamp#44643]
## Affected page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-the-css-box-model-by-building-a-rothko-painting/step-37

## Your code

```
filter: blur(2px);
```

## Expected behavior

Step 37: The directions are to `Increase the blur of .three by 2 pixels` which would be `4px`, but that is the wrong answer and the message says to set it to 2px. But it was set to `2px` in Step 35. I can change the directions to `Change` it to 2px but that doesn’t make sense because you are not actually changing it. If it should be `4px` then the solution should be changed to mark `4px` as correct. 

I am about to push 3 changes for this section and one change is for Step 36. That step says to `increase` the blur by 1px but the solution is only correct if you decrease it from 2 to 1px. I will change the wording for that lesson but should that lesson have a blur of 3px? So Step 36 may have the same issue as 37. Should the blur be 3px or 1px for 36, and should it be 4px or 2px for 37?

## Screenshots

NA

## System

- Device: [Laptop]
- OS: [Windows 10]
- Browser: [brave]
- Version: [Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (64-bit)]

**Comment by gikf** [comment]
From my understanding `filter: blur(2px)` added on `.three` element will apply another blur effect, effectively increasing the overall _bluriness_ of `.three`.

Consider example, where at that step `filter: blur(2px)` is applied to `.frame` and `filter: blur(0px)` to `.canvas`:
```css
.canvas {
  width: 500px;
  height: 600px;
  background-color: #4d0f00;
  overflow: hidden;
  filter: blur(0px);
}

.frame {
  border: 50px solid black;
  width: 500px;
  padding: 50px;
  margin: 20px auto;
  filter: blur(2px);
}
```
`.canvas` is child element of `.frame`, but it is still blurred.
