### ISSUE TITLE
Nutrition Label Ex 35-36: Should use Flexbox, not Float

### ISSUE THREAD

**Issue by SaintPeter** [freeCodeCamp/freeCodeCamp#46675]
### Describe the Issue

I was helping a camper with this challenge today and they were confused about the need to add `overflow: hidden` to the `h1` element.  I was too, until I did some research and remembered that [containers don't clear floats automatically](https://css-tricks.com/containers-dont-clear-floats/) unless you use `overflow: hidden`.  This is very counter-intuitive and is not explained at all in the challenge.

Additionally, in the next challenge you have to add a "magic number" to the h1 to get it to optically align. I don't think this scales well (literally), because if you increase your font size it's going to break.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-typography-by-building-a-nutrition-label/step-35

### Your code

```html
<div class="calories-info">
        <div class="left-container">
          <p class="bold sm-text">Amount per serving</p>
            <h1>Calories</h1>
          </div>
        <h1 class="right">230</h1>
      </div>          
```
```css
.calories-info {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
}

.left-container {
  display: flex;
  flex-direction: column;
}
```

### Expected behavior

It seems to me that there is a better, much cleaner solution to be had by applying another wrapper around the "Amount Per Serving" and "Calories" elements and using a flex column, then using flex on the `.calories-info` div with `justify-content: space-between` and `align-items: flex-end`;  

No magic numbers needed, both the markup and css are cleaner - although you do need one more containing element.

I've added a screenshot which shows the layout of the elements in my example.

### Screenshots

![image](https://user-images.githubusercontent.com/553494/175826124-d65a4ab3-7209-479c-9ed9-f7918db36916.png)

### System

N/A

### Additional context

In general, the given solution feels very "old school" to me.  Flexbox has been available on most platforms for a number of years now.  We really shouldn't be teaching people to support IE11 (especially since it has reached the end of it's support life, recently).

I know this is a big change, it just bugs me to see this being taught in what is supposed to be a modern course on the web.

**Comment by Sboonny** [comment]
At the final step, it looks the same except the font in `.calories-info span` aren't reading 

```css
.calories-info span {
  font-size: 1.2em;
}
```

anyway, I like the idea of redoing the challenge and polishing it, maybe even adding hints about grid concepts.


![image](https://user-images.githubusercontent.com/88248797/175827402-00646986-2d99-4978-a120-35b337b7a4ea.png)


here is the code, because I may have made a mistake.

<details>
 <summary> html</summary>
 
```html
 <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Nutrition Label</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <link href="./styles.css" rel="stylesheet">
  </head>
  <body>
    <div class="label">
      <header>
        <h1 class="bold">Nutrition Facts</h1>
        <div class="divider"></div>
        <p>8 servings per container</p>
        <p class="bold">Serving size <span class="right">2/3 cup (55g)</span></p>
      </header>
      <div class="divider lg"></div>
      <div class="calories-info">
        <div class="left-container">
        <p class="bold sm-text">Amount per serving</p>
        <h1>Calories </h1>
      </div>
         <span class="right">230</span>

      </div>
      <div class="divider md"></div>
      <div class="daily-value sm-text">
        <p class="right bold no-divider">% Daily Value *</p>
        <div class="divider"></div>
        <p><span class="bold">Total Fat</span> 8g <span class="bold right">10%</span></p>
        <p class="indent no-divider">Saturated Fat 1g <span class="bold right">5%</span></p>
        <div class="divider"></div>
        <p class="indent no-divider"><i>Trans</i> Fat 0g</p>
        <div class="divider"></div>
        <p><span class="bold">Cholesterol</span> 0mg <span class="right bold">0%</span></p>
        <p><span class="bold">Sodium</span> 160mg <span class="right bold">7%</span></p>
        <p><span class="bold">Total Carbohydrate</span> 37g <span class="right bold">13%</span></p>
        <p class="indent no-divider">Dietary Fiber 4g</p>
        <div class="divider"></div>
        <p class="indent no-divider">Total Sugars 12g</p>
        <div class="divider dbl-indent"></div>
        <p class="dbl-indent no-divider">Includes 10g Added Sugars <span class="right bold">20%</span>
        <div class="divider"></div>
        <p class="no-divider"><span class="bold">Protein</span> 3g</p>
        <div class="divider lg"></div>
        <p>Vitamin D 2mcg <span class="right">10%</span></p>
        <p>Calcium 260mg <span class="right">20%</span></p>
        <p>Iron 8mg <span class="right">45%</span></p>
        <p class="no-divider">Potassium 235mg <span class="right">6%</span></p>
      </div>
      <div class="divider md"></div>
      <p class="note">* The % Daily Value (DV) tells you how much a nutrient in a serving of food contributes to a daily diet. 2,000 calories a day is used for general nutrition advice.</p>
    </div>
  </body>
</html>
```
 </details>

<details>
 <summary> css</summary>
 
```css
* {
  box-sizing: border-box;
}

html {
  font-size: 16px;
}

body {
  font-family: 'Open Sans', sans-serif;
}

.label {
  border: 2px solid black;
  width: 270px;
  margin: 20px auto;
  padding: 0 7px;
}

header h1 {
  text-align: center;
  margin: -4px 0;
  letter-spacing: 0.15px
}

p {
  margin: 0;
}

.divider {
  border-bottom: 1px solid #888989;
  margin: 2px 0;
  clear: right;
}

.bold {
  font-weight: 800;
}

.right {
  float: right;
}

.lg {
  height: 10px;
}

.lg, .md {
  background-color: black;
  border: 0;
}

.md {
  height: 5px;
}

.sm-text {
  font-size: 0.85rem;
}

.calories-info {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
}

.left-container {
  display: flex;
  flex-direction: column;
}

.calories-info h1 {
  margin: -5px -2px;
}

.calories-info span {
  font-size: 1.2em;
}

.indent {
  margin-left: 1em;
}

.dbl-indent {
  margin-left: 2em;
}

.daily-value p:not(.no-divider) {
  border-bottom: 1px solid #888989;
}

.note {
  font-size: 0.6rem;
  margin: 5px 0;
}
```
 </details>
