### ISSUE TITLE
Create ControlLabel Component

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#47155]
What freeCodeCamp use https://github.com/react-bootstrap/react-bootstrap/blob/v0.33.1/src/ControlLabel.js

It has to propstype `htmlFor` and `srOnly`

Styles

```CSS
.form-horizontal .form-group-lg .control-label {
    padding-top: 11px;
    font-size: 18px;
  }
  
.form-horizontal .form-group-sm .control-label {
    padding-top: 6px;
    font-size: 12px;
  }
  
.has-success .control-label {
  color: #3c763d;
}

.has-warning .control-label {
  color: #8a6d3b;
}

.has-error .control-label {
  color: #a94442;
}

.form-inline .control-label {
    margin-bottom: 0;
    vertical-align: middle;
}

  .navbar-form .control-label {
    margin-bottom: 0;
    vertical-align: middle;
  }
  
  @media (min-width: 768px) {
  .form-horizontal .control-label {
    padding-top: 7px;
    margin-bottom: 0;
    text-align: right;
  }
  .form-horizontal .form-group-lg .control-label {
    padding-top: 11px;
    font-size: 18px;
  }
  .form-horizontal .form-group-sm .control-label {
    padding-top: 6px;
    font-size: 12px;
  }
}
  
 ```
