### ISSUE TITLE
Content error in news article  

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/freeCodeCamp#47950]
https://www.freecodecamp.org/news/github-super-linter

### Is your feature request related to a problem? Please describe.

```yaml
	  - name: Lint Code Base
        uses: github/super-linter@v4

      - name: Lint Code Base
        uses: github/super-linter@v4
```
there two `Lint Code Base`

### Describe the solution you'd like

```yaml
	  - name: Lint Code Base
        uses: github/super-linter@v4

      - name: Lint Code Base
        uses: github/super-linter@v4
```
should be only one a  `Linit Code Base` 

### Describe alternatives you've considered

should delete some  to keep one .

### Additional context

![image](https://user-images.githubusercontent.com/6524977/194762615-d9927ee5-d209-4524-9766-544944b7b064.png)
![image](https://user-images.githubusercontent.com/6524977/194762682-58ad28c6-2b69-4982-a17e-335d5f580f8f.png)
