### ISSUE TITLE
z-index mentioned in passing in balance sheet before being introduced in a later project (picasso painting)

### ISSUE THREAD

**Issue by hbar1st** [freeCodeCamp/freeCodeCamp#48874]
### Describe the Issue

In the balance sheet project step 42:
https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/step-42
The following instruction is given:
Ensure your years do not get hidden by setting a z-index of 999.

No explanation is given as to what z-index is used for other than this one line.

Not until we get to step 10 (https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-intermediate-css-by-building-a-picasso-painting/step-10) of the Picasso painting project do we see a full explanation for it.
Perhaps the explanation should be moved from the Picasso project to the Balance Sheet project?

### Affected Page

see writeup above

### Your code

```

```

### Expected behavior

Since we are asking people to set the z-index in step 42 of the balance sheet project, and since an explanation already exists for what z-index is used for but in a -later- project, maybe we should move that explanation to step 42 of the balance sheet project or at least give a longer explanation of what z-index is supposed to be doing.

### System

N/A

**Comment by naomi-lgbt** [comment]
I'm not convinced that z-index is actually necessary there, tbh.

**Comment by moT01** [comment]
I don't see the purpose of the z-index in this spot either. I vote to just remove that part from this step - it would need to be removed in the seed of the rest of the steps.

**Comment by Sboonny** [comment]
to solve this issue, remove the `z-index` from the project and its seed code.  Here is the folder https://github.com/freeCodeCamp/freeCodeCamp/tree/main/curriculum/challenges/english/14-responsive-web-design-22/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet

----

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.

**Comment by bbsmooth** [comment]
When I remove `z-index` from `#years` in the finished product then the content in the table overlaps the years heading (which is using fixed positioning).

**Comment by Sboonny** [comment]
True, should have noticed.

We can clean the extra position and weird styles for the `captian` element, and will have the position always at the top again without `z-index`

```css
/* styles.css */

span[class~="sr-only"] {
  border: 0 !important; 
  clip: rect(1px, 1px, 1px, 1px) !important;
  clip-path: inset(50%) !important;
  -webkit-clip-path: inset(50%) !important;
  height: 1px !important;
  width: 1px !important;
  position: absolute !important;
  overflow: hidden !important;
  white-space: nowrap !important;
  padding: 0 !important;
  margin: -1px !important;
}

html {
  box-sizing: border-box;
}

body {
  font-family: sans-serif;
  color: #0a0a23;
}

h1 {
  max-width: 37.25rem;
  margin: 0 auto;
  padding: 1.5rem 1.25rem;
}

h1 .flex {
  display: flex;
  flex-direction: column-reverse;
  gap: 1rem;
}

h1 .flex span:first-of-type {
  font-size: 0.7em;
}

h1 .flex span:last-of-type {
  font-size: 1.2em;
}

section {
  max-width: 40rem;
  margin: 0 auto;
  border: 2px solid #d0d0d5;
}

#years {
  display: flex;
  justify-content: flex-end;
  position: sticky;
  top: 0;
  background: #0a0a23;
  color: #fff;
  padding: 0.5rem calc(1.25rem + 2px) 0.5rem 0;
  margin: 0 -2px;
}

#years span[class] {
  font-weight: bold;
  width: 4.5rem;
  text-align: right;
}

.table-wrap {
  padding: 0 0.75rem 1.5rem 0.75rem;
}

table {
  border-collapse: collapse;
  border: 0;
  width: 100%;
  margin-top: 3rem;
}

table caption {
  color: #356eaf;
  font-size: 1.3em;
  font-weight: normal;
  float: left;
}

tbody td {
  width: 100vw;
  min-width: 4rem;
  max-width: 4rem;
}

tbody th {
  width: calc(100% - 12rem);
}

tr[class="total"] {
  border-bottom: 4px double #0a0a23;
  font-weight: bold;
}

tr[class="total"] th {
  text-align: left;
  padding: 0.5rem 0 0.25rem 0.5rem;
}

tr.total td {
  text-align: right;
  padding: 0 0.25rem;
}

tr.total td:nth-of-type(3) {
  padding-right: 0.5rem;
}

tr.total:hover {
  background-color: #99c9ff;
}

td.current {
  font-style: italic;
}

tr.data {
  background-image: linear-gradient(to bottom, #dfdfe2 1.845rem, white 1.845rem);
}

tr.data th {
  text-align: left;
  padding-top: 0.3rem;
  padding-left: 0.5rem;
}

tr.data th .description {
  display: block;
  font-weight: normal;
  font-style: italic;
  padding: 1rem 0 0.75rem;
  margin-right: -13.5rem;
}

tr.data td {
  vertical-align: top;
  padding: 0.3rem 0.25rem 0;
  text-align: right;
}
```
