### ISSUE TITLE
Refactor the tab-content from flex layout to grid layout

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#48925]
**Describe the request**
The tab-content has `flex` layout which can changed to grid because its children use specific layout. 

Flexbox doesn't provide a good way for precision, and it does attempt to provide the most available space for the content it, which cased the need to add position `relative` to it, to hide the scrollbar in small layout check https://github.com/freeCodeCamp/freeCodeCamp/pull/48231 for more context, we can change the tab-content to `grid` with 2 columns template, this will make it, so we don't need to use `position: relative`.

The issue originated because `position: relative` is breaking the work done in this PR https://github.com/freeCodeCamp/freeCodeCamp/pull/48586#pullrequestreview-1232290212, which leads to suboptimal experience for certain mobile devices.

---

To solve this issue, you need to change:

```css
#mobile-layout .tab-content {
  position: relative;
  display: flex;
  flex-direction: column;
  flex-grow: 1;
  overflow-y: hidden;
}
```

to something like:

```css
#mobile-layout .tab-content {
  display: grid;
  grid-columns-template: some math 🤔;
  overflow-y: hidden;
  height: 100vh;
  height:: 100dvh;
}
```

---

You must make sure that:

- the scroll bar doesn't show up again, that were solved in https://github.com/freeCodeCamp/freeCodeCamp/pull/48231
- the layout is responsive.

----

If you would like to fix this issue, please make sure you read [our guidelines for contributing](https://contribute.freecodecamp.org/#/), we prioritize contributors following the instructions in our guides. Join us in [our chat room](https://discord.gg/PRyKn3Vbay) or [the forum](https://forum.freecodecamp.org/c/contributors/3) if you need help contributing, our moderators will guide you through this.
