### ISSUE TITLE
Broken Tests for Media Queries

### ISSUE THREAD

**Issue by jjwall** [freeCodeCamp/freeCodeCamp#49375]
### Describe the Issue

Media Query test not passing for the Technical Documentation certification project.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/build-a-technical-documentation-page-project/build-a-technical-documentation-page

### Your code

```css
@media only screen and (max-width: 815px) {
  /* For mobile phones: */
  #navbar ul {
    border: 1px solid;
    height: 207px;
  }

  #navbar {
    background-color: white;
    position: absolute;
    top: 0;
    padding: 0;
    margin: 0;
    width: 100%;
    max-height: 275px;
    border: none;
    z-index: 1;
    border-bottom: 2px solid;
  }

  #main-doc {
    position: relative;
    margin-left: 0px;
    margin-top: 270px;
  }
}

@media only screen and (max-width: 400px) {
  #main-doc {
    margin-left: -10px;
  }

  code {
    margin-left: -20px;
    width: 100%;
    padding: 15px;
    padding-left: 10px;
    padding-right: 45px;
    min-width: 233px;
  }
}
```

### Expected behavior

Given the fact that I'm adding a @media query in my CSS, I would expect the media query test to pass in the console.

### Screenshots

![image](https://user-images.githubusercontent.com/22758295/218600850-33e3ad75-59a6-4c9f-b81c-4d84b2732b54.png)

### System

- Device: [MacBook Air]
- OS: [MacOS Big Sur 11.6.8]
- Browser: [Chrome 102]
- Version: [e.g. 22]

### Additional context

This problem is happening for the media query test on the Product Landing Page project, as well as on the Personal Portfolio Page project.
