### ISSUE TITLE
Stacking the element concept is taught incorrectly in the balance sheet

### ISSUE THREAD

**Issue by Sboonny** [freeCodeCamp/freeCodeCamp#49742]
Although it's fine to teach people the wrong way, then correct it to make a concept clearer, we shouldn't be teaching people to fail.
---

## The issue

In [step 43](https://github.com/freeCodeCamp/freeCodeCamp/blob/f578a22c999c50e766e4a243e7ed40418a776534/curriculum/challenges/english/14-responsive-web-design-22/learn-more-about-css-pseudo-selectors-by-building-a-balance-sheet/64076bbeba941114b0027b6a.md?plain=1#L2), we are asking the campers to add `z-index`, to keep the stacking on the top, but this is the wrong way of using stacking because you don't need to introduce other stacking to have the same effect.

In matter of fact teaching campers to introduce other stacking, without reason, creates the habit to ignore the consequences of doing so, and how can introducing a stack break the layout, specially as float values don't respect other elements in the page, and can even affect hidden section that most people don't think about like scroll bars.

---

## How is this isn't necessary?

If you remove the `z-index`, then it breaks the sticky bar in the mobile layout, if you choose to make it wide screen, but we actually don't need to account for that, because the issue in the layout happens when we add `position` properties to the table, which introduce another stack, that should be respected while it isn't needed.

Here are the properties 

```css
table {
  position: relative;
}

table caption {
  position: absolute;
}
```

----

## What I think, we should do?

I think it's good to teach how failing is like, but we shouldn't teach people to fail, because people do use our curriculum to get jobs, and if we are teaching people to add stacks that can easily introduce weird bugs, that's harmful and risk people losing gigs.

And the project doesn't need it, so it's win-win fewer steps and better teaching materials

---

Note: the code at the end could look like this

```css
table {
  border-collapse: collapse;
  border: 0;
  width: 100%;
}

table caption {
  color: #356eaf;
  font-size: 1.3em;
  font-weight: normal;
  margin: .5rem;
  text-align: left;
}
```
