### ISSUE TITLE
Accessibility Quiz step 48: a better solution?

### ISSUE THREAD

**Issue by leonfeng** [freeCodeCamp/freeCodeCamp#52414]
### Describe the Issue

The template answer for the second part of this challenge is `position: fixed`. According to MDN, with [`fixed`](https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed):

> The element is removed from the normal document flow, and no space is created for the element in the page layout.

As a result, the `header` covers the first `h2`, Student Info.

Whereas [`position: sticky`](https://developer.mozilla.org/en-US/docs/Web/CSS/position#sticky) does not have this effect.

> The offset does not affect the position of any other elements.

_Before: Student Info is visible_
![Screenshot 2023-11-22 224155](https://github.com/freeCodeCamp/freeCodeCamp/assets/53984269/2467dc05-8038-4f98-87ff-4b56dcc53cc8)

_After adding `position: fixed`: Student Info is covered_
![Screenshot 2023-11-22 224233](https://github.com/freeCodeCamp/freeCodeCamp/assets/53984269/c3be1249-e709-4663-a6c2-53a41515215f)

_After adding `position: sticky`: Student Info is visible_
![Screenshot 2023-11-22 224433](https://github.com/freeCodeCamp/freeCodeCamp/assets/53984269/968cd70c-f8f6-477f-a309-0716f37d3a0e)

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-48

### Your code

```css
header {
  width: 100%;
  height: 50px;
  background-color: #1b1b32;
  display: flex;
  justify-content: space-between;
  align-items: center;
  position: sticky;
  top: 0;
}
```

### Expected behavior

My code passes the tests.

### System

- Device: Laptop
- OS: Windows 11
- Browser: Edge
- Version: 119
