### ISSUE TITLE
Accessibility Quiz step 47 should accept multiple valid CSS selectors

### ISSUE THREAD

**Issue by leonfeng** [freeCodeCamp/freeCodeCamp#52412]
### Describe the Issue

Multiple CSS selectors are valid for this challenge, but only `nav > ul > li:hover` and `nav li:hover` pass the tests.

### Affected Page

https://www.freecodecamp.org/learn/2022/responsive-web-design/learn-accessibility-by-building-a-quiz/step-47

### Your code

```css
nav > ul > li > a:hover {
  background-color: #dfdfe2;
  color: #1b1b32;
  cursor: pointer;
}

li > a {
  color: inherit;
  text-decoration: none;
}
```

### Expected behavior

My code passes the tests.

### System

- Device: Laptop
- OS: Windows 11
- Browser: Edge
- Version: 119
