### ISSUE TITLE
[New JS projects] Text within `select` elements is not aligned vertically in Firefox

### ISSUE THREAD

**Issue by mmatsumoto1026** [freeCodeCamp/freeCodeCamp#52747]
### Describe the Issue

In [Learn Basic Algorithmic Thinking by Building a Number Sorter challenges](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-algorithmic-thinking-by-building-a-number-sorter/step-1), the text within `select` elements is not aligned center vertically only in Firefox browser, as shown in below screenshot.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-algorithmic-thinking-by-building-a-number-sorter/step-1

### Your code

```css
select {
  font-family: inherit;
  font-size: inherit;
  line-height: inherit;
  min-height: 38px;
  width: 50px;
  text-align: center;
}
```

### Expected behavior

Like Other browsers(i.e. Chrome, edge), show the text in `select` element with aligning vertically center in Firefox. 

### Screenshots

![text_within_select_elements_are_not_aligned](https://github.com/freeCodeCamp/freeCodeCamp/assets/44451585/87e164b0-f556-4d7e-91e4-85d1526be162)

### System

- Device: Windows laptop PC 
- OS: Windows 11 Home
- Browser: Firefox
- Version: 121.0(64 bit)

### Additional context

It seems that by `min-height` property the text is pushed to top of the select element.
