### ISSUE TITLE
[The Odin Project] Issues in Learn CSS Foundations Projects - CSS Foundations Exercise B

### ISSUE THREAD

**Issue by huyenltnguyen** [freeCodeCamp/freeCodeCamp#52819]
### Describe the Issue

There are a couple of issues in Learn CSS Foundations Projects - CSS Foundations Exercise B.

- In the solution code, the background color of `.odd` should be `yellow` instead of `rgb(255, 167, 167)`
- The "Your odd elements should have a `background-color` of `yellow`" check doesn't have an assertion, which allows any color as background color.
  - To reproduce, use the solution code in the challenge file and modify as follows:
      ```css
      /* css */
      .odd {
        background-color: white; /* changed line */
        font-family: Verdana, "DejaVu Sans", sans-serif; 
      }
      ```
- The "Your second element should have `blue` text and a `font-size` of `36px`" check fails if the color is set to `blue`, but passes if the color is set to `#0000ff`.
  - To reproduce, use the solution code in the challenge file and modify as follows:
      ```css
      /* css */
      #two {
        color: blue; /* changed line */
        font-size: 36px;
      }
      ```

Link to the challenge file: https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/16-the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-b.md.

### Affected Page

https://www.freecodecamp.org/learn/the-odin-project/top-learn-css-foundations-projects/css-foundations-exercise-b

### Expected behavior

I'm not entirely sure about the purpose of the backticks in color names. Looking at the tests, I don't think we care about the actual color names in the stylesheet but only the computed color values. So maybe the tests should be relaxed and the instructions should be updated to remove the backticks.

Here is the list of items I think we should change:
- ~~Remove backticks from `yellow`, `red`, and `blue`~~
- In the solution code, change the background color of `.odd` to `yellow`
- Add an assertion to the "Your odd elements should have a `background-color` of `yellow`" check
- Update the "Your second element should have `blue` text and a `font-size` of `36px`" check to look for the value `blue`
- ~~Update the "The fourth element should have a `red` `background-color`" check to use `getComputedStyle()`, and the expected color value should be `rgb(255, 0, 0)`~~
