### ISSUE TITLE
RPG Step 11 Rejects Valid Code

### ISSUE THREAD

**Issue by jeremylt** [freeCodeCamp/freeCodeCamp#52956]
### Describe the Issue

Below is syntactically valid code that meets the challenge description. The error message says

> You should have a `#controls, #stats selector`.

but we've adopted a policy of accepting any valid syntax that meets the challenge description, so I think we need to check that the target elements received the desired style.

### Affected Page

https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures-v8/learn-basic-javascript-by-building-a-role-playing-game/step-11

### Your code

```CSS
#controls {
  border: 1px solid #0a0a23;
  padding: 5px;
  color: #0a0a23;
}

#stats {
  border: 1px solid #0a0a23;
  padding: 5px;
  color: #0a0a23;
}
```

### Expected behavior

Valid code should be accepted.

### System

All
