### ISSUE TITLE
[ Full Stack Cert ] - update demo and add missing information for event flyer lab

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#56874]
There are a few things that need to be updated in the lab.

The first thing is that the message for reminding campers to link their CSS to the HTML document is missing.

Here is the massage we use

```md
**Note:** Be sure to link your stylesheet in your HTML and apply your CSS.
```

This message needs to go just before the `# --hints--`

Then in the `# --solutions--` section, the height seems off here

![Image](https://github.com/user-attachments/assets/97429da3-3a80-432b-828b-9fa2b806c68f)

Using `min-height` for the `body` selector resolves that

```css
body {
  padding: 50px 10px;
  margin: 0 auto;
  width: 90vw;
  min-height: calc(100vh - 100px); 
  background-color: white;
  font-family: sans-serif;
  text-align: center;
}

```

Here is the file you need to update

https://github.com/freeCodeCamp/freeCodeCamp/blob/main/curriculum/challenges/english/25-front-end-development/lab-event-flyer-page/66e45c8140f9fda5c105ae26.md
