### ISSUE TITLE
Navbar style breaks in high contrast mode due to transparency/white background

### ISSUE THREAD

**Issue by MohamadSalman11** [freeCodeCamp/freeCodeCamp#58807]
### Describe the Issue

In high contrast mode, the navigation does not appear as expected, leading to a poor user experience for those who enable high contrast mode. The issue only occurs in light high contrast mode, where the navbar becomes transparent or white, breaking the entire design. This issue does not happen in dark high contrast mode, where the navbar appears as intended.

If all of the below makes sense, I will be very happy to make my first pull request 😀

### Affected Page

https://www.freecodecamp.org

### Steps to Reproduce

Following suggestions fix the issue (I am glad to hear any feedback):

```css
.universal-nav {
  align-items: center;
  background-color: var(--theme-color);
  color: var(--gray-00);
  display: flex;
  font-size: 18px;
  height: var(--header-height);
  justify-content: space-between;
  padding: 0 5px;
  forced-color-adjust: none;
}

@media (min-width: 401px) {
  .universal-nav {
    background-color: var(--theme-color);
  }
}
```

### Expected behavior

We need to handle the background color in high contrast mode.

### Screenshots

Before:
![Image](https://github.com/user-attachments/assets/54d98edb-b2ad-4bc4-960e-95770a1d66a8)

After my suggestion:

![Image](https://github.com/user-attachments/assets/b0b7c563-4bc3-46ca-b09e-6d6ef79c9862)

### System

- Device: Laptop
- OS: Windows 10
- Browser: Chrome
