### ISSUE TITLE
Updates to favorite icon toggler

### ISSUE THREAD

**Issue by jdwilkin4** [freeCodeCamp/freeCodeCamp#59481]
I was testing out this project and found a few things that need changing.

https://www.freecodecamp.org/learn/full-stack-developer/lab-favorite-icon-toggler/build-a-favorite-icon-toggler

## First change

We shouldn't be using `span` elements. We should use `button` elements instead. That way this can be keyboard accessible where I can tab through the list and hit enter to fill the heart and unfill it.
These changes needs to be updated in the final solution, user stories, hints and tests.

## Second change

There is an empty `title` element in the `## --seed-contents--` here.

```html
<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="styles.css">
</head>
```

That should be updated to this instead

```html
<head>
    <meta charset="utf-8">
    <title>Favorite Icon Toggler</title>
    <link rel="stylesheet" href="styles.css">
</head>
```

## Third change

The last sentence before the user stories tells campers not to copy the demo project

<img width="527" alt="Image" src="https://github.com/user-attachments/assets/3a1fcfe1-84fa-4734-a533-4bf1c395673b" />

However, there is already mention of that in the introductory paragraph. So that last sentence of `Do not copy this demo project.` should be removed. 

## Fourth change

The other labs have a note telling campers to not forget about linking their JS file to the HTML file. But this lab doesn't say that. 

So this not should be added after the user stories

```md
**Note:** Be sure to link your JavaScript file in your HTML. (Ex. `<script src="script.js"></script>`)
```

## Fifth change

The final solution is using pixels for the `font-size` here

```css
.favorite-icon {
    font-size: 20px;
    cursor: pointer;
}
```

We should avoid using pixels here and instead use something like `rem`. Also since this will now be a button, we should add the button styles too.

```css
.favorite-icon {
    font-size: 1.25rem;
    background-color: transparent;
    border: none;
    cursor: pointer;
}
```

## Last change

The lab has campers add a `filled` class but the final solution never uses it. It would make sense to add some styles to the `filled` class like having the filled heart be red.

```css
.filled {
    color: #D22B2B;
}
```
