### ISSUE TITLE
Build an availability table issue

### ISSUE THREAD

**Issue by BDubDesigns** [freeCodeCamp/freeCodeCamp#59969]
### Describe the Issue

I was doing this lab, and was failing: "35. You should use two color-stops (expressed in percentage) to make the transition from one color to the following color a hard line for your #legend-gradient. Remember to use your --color# variables." from this user story: "You should give the #legend-gradient element a linear gradient that transitions between all the colors from --color0 to --color5. Each color value should have two color stops (expressed as percentages) to make the transition between colors a hard line."
I was using 2 color stops the way that the previous lesson, a workshop on city skylines, used gradients for hard color stops. While I understand that the city skyline lesson is about variables, not linear-gradients, its still the most recent interaction with linear-gradients, and I'd argue you interact with gradients much more than variables in that lesson anyway. 

It would be helpful if either a.) the build an availability table tests allowed for that syntax to work, as it does display the gradient correctly and it is the way that the previous workshop demonstrates, b.) the user stories / test failing was more clear about the syntax it requires to pass, or c.) perhaps change the previous lesson to show the more concise syntax that the test is looking for? The actual linear-gradients section probably explained how to do color stops this way, but if its been a few days since you've done that section, it can be confusing for the test to fail when you are doing things the way you were most recently shown (in the city skyline workshop that immediately precedes this lab).

Thanks!

### Affected Page

https://www.freecodecamp.org/learn/full-stack-developer/lab-availability-table/build-an-availability-table

### Your code

The code that failed:
```
#legend-gradient {
  background-image: linear-gradient(90deg,
    var(--color0) 0%,
    var(--color0) 16%,
    var(--color1) 16%,
    var(--color1) 33%,
    var(--color2) 33%,
    var(--color2) 50%,
    var(--color3) 50%,
    var(--color3) 66%,
    var(--color4) 66%,
    var(--color4) 83%,
    var(--color5) 83%,
    var(--color5) 100%
  );
}
```
 This was the code that ended up passing:
```
#legend-gradient {
  background-image: linear-gradient(90deg,
    var(--color0) 0% 16%,
    var(--color1) 16% 33%,
    var(--color2) 33% 50%,
    var(--color3) 50% 66%,
    var(--color4) 66% 83%,
    var(--color5) 83% 100%
  );
}```


### Expected behavior

I expected my code to make test 35 pass but it didnt.

### Screenshots

_No response_

### System

- Device: Predator Helios Neo 14 Laptop
- OS: Windows 11
- Browser: chrome
- Version: lts


### Additional context

_No response_

**Comment by jdwilkin4** [comment]
Since this has come up a few times, we can update the tests to accept the first version here since that is what campers will be more familiar with.

```css
#legend-gradient {
  background-image: linear-gradient(90deg,
    var(--color0) 0%,
    var(--color0) 16%,
    var(--color1) 16%,
    var(--color1) 33%,
    var(--color2) 33%,
    var(--color2) 50%,
    var(--color3) 50%,
    var(--color3) 66%,
    var(--color4) 66%,
    var(--color4) 83%,
    var(--color5) 83%,
    var(--color5) 100%
  );
}
```
