### ISSUE TITLE
Full Stack Curriculum: CSS Lecture Quiz assumes knowledge of concepts not yet introduced

### ISSUE THREAD

**Issue by igorgetmeabrain** [freeCodeCamp/freeCodeCamp#60634]
# Certified Full Stack Developer Curriculum

## What is CSS?

[How do height and width work?](https://www.freecodecamp.org/learn/full-stack-developer/lecture-what-is-css/how-do-width-and-height-work)

In the lecture linked above, the following question and answer are presented:

> QUESTION: Which of the following units can be used to set the width or height of an element?

> CORRECT ANSWER: `px`, `%`, and `em`.

However, the concept of `em` and `rem` have not yet been introduced by this point.

The video transcript includes the following explanation:
> These properties can be defined in different units such as pixels (`px`), percentages (`%`), viewport units (`vw`, `vh`), and more.

Perhaps the correct answer to the above question should not include `em` but instead `vw` or `vh`?

**Comment by jdwilkin4** [comment]
We can use a different question there.

It would be nice to have a question around a code example.
maybe something around this example?

```css
   .box {
      width: 200px;
      max-width: 150px;
      height: 200px;
      max-height: 150px;
      background-color: lightgreen;
    }
```
